[config]

[config.custom_colors]
term_red = "#f38ba8"
term_green = "#a6e3a1"
term_yellow = "#f9e2af"
term_blue = "#89b4fa"
term_magenta = "#cba6f7"
term_cyan = "#94e2d5"
term_orange = "#fab387"

[templates.delta]
input_path = "~/.config/matugen/delta.gitconfig"
output_path = "~/.config/delta/matugen.gitconfig"

[templates.bat]
input_path = "~/.config/matugen/bat-matugen.tmTheme"
output_path = "~/.config/bat/themes/matugen.tmTheme"
post_hook = "bat cache --build"

[templates.fuzzel]
input_path = "~/.config/matugen/fuzzel.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.ghostty]
input_path = "~/.config/matugen/ghostty"
output_path = "~/.config/ghostty/themes/matugen.conf"
post_hook = "kill -SIGUSR2 $(pgrep ghostty)"

[templates.hyprland]
input_path = "~/.config/matugen/hyprland-colors.conf"
output_path = "~/.config/hypr/hyprland/colors.conf"
post_hook = "hyprctl reload"

[templates.nvim]
input_path = "~/.config/matugen/nvim-base16-colorscheme.lua"
output_path = "~/.config/nvim/generated.lua"
post_hook = "pkill -SIGUSR1 nvim"

[templates.vscode]
input_path = "~/.config/matugen/vscode-matugen-theme.json"
output_path = "~/.vscode/extensions/custom.matugen-theme-1.0.0/themes/matugen-color-theme.json"

[templates.quickshell]
input_path = "~/.config/matugen/quickshell-colors"
output_path = "~/.config/quickshell/common/Colors.qml"
