#=== HYPRLAND
[".config/hypr/contrib"]
  type = "git-repo"
  url = "https://github.com/hyprwm/contrib"
  refreshPeriod = "168h"

#=== TMUX
[".config/tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  refreshPeriod = "168h"

#=== ZSH
[".zsh/pure"]
  type = "git-repo"
  url = "https://github.com/sindresorhus/pure"
  refreshPeriod = "168h"

[".zsh/gitstatus"]
  type = "git-repo"
  url = "https://github.com/romkatv/gitstatus"
  refreshPeriod = "168h"

[".zsh/plugins/zsh-syntax-highlighting"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting"
  refreshperiod = "168h"

[".zsh/plugins/zsh-history-substring-search"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-history-substring-search"
  refreshperiod = "168h"

[".zsh/plugins/zsh-autosuggestions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-autosuggestions"
  refreshPeriod = "168h"

[".zsh/plugins/zsh-vi-mode"]
  type = "git-repo"
  url = "https://github.com/jeffreytse/zsh-vi-mode"
  refreshPeriod = "168h"

[".zsh/plugins/fzf-tab"]
  type = "git-repo"
  url = "https://github.com/Aloxaf/fzf-tab"
  refreshPeriod = "168h"

[".zsh/plugins/zsh-ssh"]
  type = "git-repo"
  url = "https://github.com/sunlei/zsh-ssh"
  refreshPeriod = "168h"

#=== THEMES
["Themes/catppuccin/fuzzel"]
  type = "git-repo"
  url = "https://github.com/catppuccin/fuzzel"
  refreshPeriod = "168h"

[".config/btop/themes"]
  type = "archive"
  url = "https://github.com/catppuccin/btop/releases/download/1.0.0/themes.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/delta/themes/catppuccin"]
  type = "git-repo"
  url = "https://github.com/catppuccin/delta"
  refreshPeriod = "168h"
