pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

QtObject {
    id: config

    // Matugen reload trigger — watches a sentinel file written by matugen's post_hook
    property FileView matugenReloadTrigger: FileView {
        path: "/home/sboynton/.cache/matugen/quickshell-reload-trigger"
        watchChanges: true
        onFileChanged: {
            console.log("[Config] Matugen colors updated, reloading shell...")
            Quickshell.reload()
        }
    }

    // All colors derived from Colors.qml (generated by pywal16)

    // Returns readable text color (dark or light) for any background
    function contrastText(bg) {
        const hex = bg.toString()
        const r = parseInt(hex.substring(1, 3), 16) / 255
        const g = parseInt(hex.substring(3, 5), 16) / 255
        const b = parseInt(hex.substring(5, 7), 16) / 255
        const lum = 0.299 * r + 0.587 * g + 0.114 * b
        return lum > 0.45 ? "#1a1a1a" : "#f0f0f0"
    }

    // Primary text color for bar pill indicators
    readonly property color barTextColor: contrastText(Colors.color1)

    // User configuration system
    property var userConfig: ({})
    property bool userConfigInitialized: false

    // Updates configuration
    readonly property var criticalPackages: userConfig.updates?.criticalPackages || []
    readonly property var warningPackages: userConfig.updates?.warningPackages || []

    property FileView userConfigFile: FileView {
        path: Qt.resolvedUrl("config.json")
        watchChanges: true

        onLoaded: {
            try {
                config.userConfig = JSON.parse(text())
                if (config.userConfigInitialized) {
                    console.log("[Config] *** FILE CHANGED *** User config reloaded")
                } else {
                    console.log("[Config] Initial user config load")
                    config.userConfigInitialized = true
                }
            } catch (e) {
                console.error("[Config] Failed to parse config.json:", e)
                config.userConfig = getDefaultUserConfig()
            }
        }

        onFileChanged: {
            console.log("[Config] User config file change detected, reloading...")
            reload()
        }

        onLoadFailed: {
            console.log("[Config] config.json not found, using defaults")
            config.userConfig = getDefaultUserConfig()
        }
    }

    function getDefaultUserConfig() {
        return {
            "updates": {
                "criticalPackages": [],
                "warningPackages": []
            }
        }
    }

    // Check if a package name matches a single pattern
    // Supports glob-style wildcards:
    //   "hyprland"  - exact match only
    //   "hyprland*" - starts with "hyprland"
    //   "*hyprland" - ends with "hyprland"
    //   "*hyprland*" - contains "hyprland"
    function matchesPattern(packageName, pattern) {
        var lowerName = packageName.toLowerCase()
        var lowerPattern = pattern.toLowerCase()
        var startsWithWild = lowerPattern.charAt(0) === '*'
        var endsWithWild = lowerPattern.charAt(lowerPattern.length - 1) === '*'
        var core = lowerPattern
        if (startsWithWild) core = core.substring(1)
        if (endsWithWild) core = core.substring(0, core.length - 1)

        if (startsWithWild && endsWithWild) {
            return lowerName.indexOf(core) !== -1
        } else if (startsWithWild) {
            return lowerName.substring(lowerName.length - core.length) === core
        } else if (endsWithWild) {
            return lowerName.substring(0, core.length) === core
        } else {
            return lowerName === lowerPattern
        }
    }

    // Check if a package name matches any pattern in a list
    function matchesPatternList(packageName, patternList) {
        if (!packageName || !patternList || patternList.length === 0) return false
        for (var i = 0; i < patternList.length; i++) {
            if (matchesPattern(packageName, patternList[i])) return true
        }
        return false
    }

    // Returns priority: 2 = critical, 1 = warning, 0 = normal
    function getPackagePriority(packageName) {
        if (matchesPatternList(packageName, criticalPackages)) return 2
        if (matchesPatternList(packageName, warningPackages)) return 1
        return 0
    }
    
    // getColor(path, [background]) — optional background for text contrast
    // Colors mapped to pywal ANSI roles:
    //   bg/color0  = dark background
    //   color8     = bright background (panels, hover)
    //   color1-6   = accent colors
    //   color7/fg  = foreground text
    //   color9-14  = bright accent variants
    function getColor(path, bg) {
        switch (path) {
        // Backgrounds — layered dark theme tinted toward panel accent (color5)
        // crust (deepest) → mantle → secondary → primary → tertiary → surface → overlay
        case "background.crust":     return Qt.darker(Colors.color5, 3.0)
        case "background.mantle":    return Qt.darker(Colors.color5, 2.6)
        case "background.secondary": return Qt.darker(Colors.color5, 2.2)
        case "background.primary":   return Qt.darker(Colors.color5, 1.8)
        case "background.bar":       return Qt.lighter(Colors.color7, 1.1)
        case "background.tertiary":  return Qt.darker(Colors.color5, 1.5)
        case "background.surface":   return Qt.darker(Colors.color5, 1.2)
        case "background.overlay":   return Qt.darker(Colors.color5, 2.2)

        // Text
        case "text.primary":
        case "text.light":
        case "text.white":           return Qt.lighter(Colors.fg, 1.2)
        case "text.secondary":       return Colors.fg
        case "text.tertiary":
        case "text.muted":           return Qt.lighter(Colors.color5, 2.0)

        // Borders — tinted toward accent
        case "border.primary":       return Qt.darker(Colors.color5, 1.2)
        case "border.secondary":
        case "border.subtle":        return Qt.darker(Colors.color5, 1.5)
        case "border.accent":        return Colors.color1

        // Accent colors — mapped to pywal's 6 accent slots
        case "primary.blue":
        case "state.info":           return Colors.color4
        case "primary.lavender":     return Colors.color12
        case "primary.sky":
        case "primary.sapphire":     return Colors.color4
        case "primary.green":
        case "state.success":        return Colors.color2
        case "primary.teal":         return Colors.color6
        case "primary.yellow":
        case "state.warning":        return Colors.color3
        case "primary.purple":
        case "primary.mauve":        return Colors.color5
        case "primary.pink":
        case "primary.flamingo":
        case "primary.rosewater":    return Colors.color13
        case "primary.peach":
        case "primary.orange":       return Colors.color11
        case "primary.hotpink":      return Colors.color1
        case "primary.red":
        case "state.error":          return Colors.color1
        case "primary.maroon":
        case "state.critical":       return Colors.color9
        case "state.inactive":       return Colors.color8

        // Interactive — tinted toward accent
        case "interactive.default":  return Qt.darker(Colors.color5, 1.8)
        case "interactive.hover":    return Qt.darker(Colors.color5, 1.4)
        case "interactive.pressed":  return Qt.darker(Colors.color5, 1.1)

        // Transparency
        case "transparency.track":      return "#50ffffff"
        case "transparency.background": return "#80000000"
        case "transparency.shadow":     return "#00000060"

        // Semantic aliases
        case "workspace.active":       return Colors.color4
        case "workspace.occupied":     return Colors.color8
        case "workspace.empty":        return Colors.color0
        case "battery.charging":
        case "battery.high":           return Colors.color2
        case "battery.medium":         return Colors.color3
        case "battery.low":            return Colors.color11
        case "battery.critical":       return Colors.color1
        case "battery.unavailable":    return Colors.color8
        case "volume.muted":           return Colors.color8
        case "volume.default":         return Colors.fg
        case "notification.background": return Qt.darker(Colors.color5, 2.2)
        case "notification.border":    return Qt.darker(Colors.color5, 1.5)
        case "notification.active":    return Colors.color1
        case "notification.inactive":  return Qt.darker(Colors.color5, 1.8)
        case "notification.accent":    return Colors.color13
        case "notification.text":      return Qt.lighter(Colors.fg, 1.2)
        case "notification.close":     return Colors.color1
        case "notification.closePressed": return Colors.color9
        case "osd.background":         return "#80000000"
        case "osd.track":              return "#50ffffff"
        case "osd.fill":               return Colors.fg
        case "tooltip.background":     return Qt.darker(Colors.color5, 2.2)
        case "tooltip.border":         return Qt.darker(Colors.color5, 1.5)
        case "tooltip.text":           return Qt.lighter(Colors.fg, 1.2)
        case "tooltip.shadow":         return "#00000060"

        default:
            console.warn("[Config] Unknown color path:", path)
            return Colors.color8
        }
    }

    // Font families
    readonly property string fontFamilyMonospace: "JetBrainsMono Nerd Font Propo"
    readonly property string fontFamilyIcon: "JetBrainsMono Nerd Font Propo"

    // Font size scale
    readonly property int fontSizeSmall: 11      // timestamps, version strings, priority icons
    readonly property int fontSizeBase: 11       // bar indicator text
    readonly property int fontSizeMedium: 12     // tooltips, notification body, secondary text
    readonly property int fontSizeLarge: 13      // notification summary, emphasized text
    readonly property int fontSizeHeader: 14     // panel headers
    readonly property int fontSizeIconSmall: 16  // bar icon glyphs
    readonly property int fontSizeIconMedium: 18 // menu button icons
    readonly property int fontSizeIconLarge: 24  // OSD icons
    readonly property int fontSizeIconXL: 32     // loading spinners, empty state icons

    // Bar dimensions
    readonly property int barHeight: 34
    readonly property int barRadius: 1
    readonly property string barBackgroundColor: "transparent"

    // Bar layout spacing
    readonly property int barContentLeftMargin: 4
    readonly property int barContentRightMargin: 4
    readonly property int barContentSpacing: 4

    // Pill (BarGroup) styling
    readonly property int pillVerticalMargin: 5
    readonly property int pillHorizontalPadding: 8
    readonly property int pillRadius: 6
    readonly property int pillSpacing: 4

    // Legacy BarGroup compat
    readonly property int groupBackgroundMarginLeft: 0
    readonly property int groupBackgroundMarginRight: 0
    readonly property int groupBorderWidth: 0
    readonly property int groupRadius: pillRadius
    readonly property string groupBorderColor: "transparent"
    readonly property int groupColumnSpacing: 4
    readonly property int groupRowSpacing: 12
    readonly property int groupImplicitWidthPadding: pillHorizontalPadding * 2

    // Pill colors — cycle through pywal accents (1-6) and their bright variants (9-14)
    readonly property color pillColor1:  Colors.color1
    readonly property color pillColor2:  Colors.color12  // workspaces (bright variant)
    readonly property color pillColor3:  Colors.color3
    readonly property color pillColor4:  Colors.color4
    readonly property color pillColor5:  Colors.color5
    readonly property color pillColor6:  Colors.color6
    readonly property color pillColor7:  Colors.color9
    readonly property color pillColor8:  Colors.color14  // disk (bright variant)
    readonly property color pillColor9:  Colors.color11
    readonly property color pillColor10: Colors.color12
    readonly property color pillColor11: Colors.color13
    readonly property color pillColor12: Colors.color14

    // Workspace indicators
    readonly property int workspaceSpacing: 8
    readonly property int workspaceWidth: 18
    readonly property int workspaceHeight: 14
    readonly property int workspaceRadius: 4
    readonly property int workspaceFontSize: fontSizeBase
    readonly property int workspaceBorderWidth: 2
    readonly property string workspaceActiveColor: getColor("workspace.active")
    readonly property string workspaceActiveBrightColor: getColor("workspace.active")
    readonly property string workspaceOccupiedColor: getColor("workspace.occupied")
    readonly property string workspaceEmptyColor: getColor("workspace.empty")
    readonly property string workspaceActiveBorderColor: getColor("workspace.active")
    readonly property string workspaceActiveTextColor: getColor("text.white")
    readonly property string workspaceOccupiedTextColor: getColor("text.light")
    readonly property string workspaceEmptyTextColor: getColor("text.muted")

    // Battery indicator
    readonly property int batteryFontSize: fontSizeBase
    readonly property int batterySpacing: 4
    readonly property string batteryTextColor: getColor("text.white")
    
    // Battery gauge (circular)
    readonly property int batteryGaugeOffset: 14  // Subtracted from barHeight for gauge size
    readonly property int batteryGaugeLineWidth: 2
    readonly property real batteryGaugeBackgroundOpacity: 0.3
    readonly property real batteryGaugeFontSizeMultiplier: 1
    
    // Battery threshold values (as percentages 0.0-1.0)
    readonly property real batteryCriticalThreshold: 0.15  // 15%
    readonly property real batteryLowThreshold: 0.30       // 30%
    readonly property real batteryMediumThreshold: 0.50    // 50%
    
    // Battery gauge colors
    readonly property string batteryUnavailableColor: getColor("battery.unavailable")
    readonly property string batteryChargingColor: getColor("battery.charging")
    readonly property string batteryHighColor: getColor("battery.high")
    readonly property string batteryMediumColor: getColor("battery.medium")
    readonly property string batteryLowColor: getColor("battery.low")
    readonly property string batteryCriticalColor: getColor("battery.critical")

    // Volume colors
    readonly property string volumeMutedColor: getColor("volume.muted")
    readonly property string volumeDefaultColor: getColor("volume.default")

    // Clock widget
    readonly property string clockTextColor: getColor("text.white")
    readonly property int clockFontSize: fontSizeHeader

    // Animation durations
    readonly property int colorAnimationDuration: 200
    
    // Notification system colors
    readonly property string notificationBackgroundColor: getColor("notification.background")
    readonly property string notificationBorderColor: getColor("notification.border")
    readonly property string notificationActiveColor: getColor("notification.active")
    readonly property string notificationInactiveColor: getColor("notification.inactive")
    readonly property string notificationActiveAccentColor: getColor("notification.accent")
    readonly property string notificationTextPrimaryColor: getColor("notification.text")
    readonly property string notificationTextSecondaryColor: Colors.fg
    readonly property string notificationTextTertiaryColor: getColor("text.muted")
    readonly property string notificationCloseColor: getColor("notification.close")
    readonly property string notificationClosePressedColor: getColor("notification.closePressed")
    readonly property string notificationButtonColor: getColor("interactive.default")
    readonly property string notificationButtonPressedColor: getColor("interactive.pressed")
    
    // OSD (On-Screen Display) colors
    readonly property string osdBackgroundColor: getColor("osd.background")
    readonly property string osdTrackColor: getColor("osd.track")
    readonly property string osdFillColor: getColor("osd.fill")
    
    // Tooltip colors
    readonly property string tooltipBackgroundColor: getColor("tooltip.background")
    readonly property string tooltipBorderColor: getColor("tooltip.border")
    readonly property string tooltipShadowColor: getColor("tooltip.shadow")
    readonly property string tooltipTextColor: getColor("tooltip.text")
    readonly property real tooltipShadowOpacity: 0.3
    
    // System Tray configuration
    readonly property var sysTrayPinnedItems: []  // Array of item IDs to pin (empty = auto-pin first 3)
    readonly property int sysTrayMaxPinnedItems: 3
    readonly property int sysTrayOverflowColumns: 4
    
    // Bar configuration options  
    readonly property var options: ({
        bar: {
            vertical: false,
            bottom: false,
            tray: {
                pinnedItems: [],
                invertPinnedItems: false,
                monochromeIcons: false  // Disable monochrome for better visibility
            }
        }
    })
    
    // Common sizing and timing
    readonly property int brightnessCheckInterval: 100  // milliseconds
    readonly property int clockUpdateInterval: 1000     // milliseconds
}
