swipe:
  3: 
    left: 
      command: 'xdotool key alt+Left'
    right: 
      command: 'xdotool key alt+Right'
    up: 
      command: 'xdotool key super'
    #down: 
      #command: 'xdotool key super'
# in and out appear to be reversed, or refer to the origin, e.g. 'in' = 'from in to out', 'out' = 'from out to in'
pinch: 
  #in:
    #command: 'xdotool key ctrl+t'
  out:
    command: 'xdotool key ctrl+w'

threshold:
  swipe: 0.4
  pinch: 0.8

interval:
  swipe: 0.8
  pinch: 0.1
