--disable-pinch
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoEncoder,UseMultiPlaneFormatForHardwareVideo,TouchpadOverscrollHistory,SystemNotifications,NativeNotifications
--ozone-platform-hint=auto
--enable-wayland-ime=true
