theme = "personal"

[notifications]
monitor = "DP-2"

[[bars]]
name = "top-bar"
edge = "top"
monitors = ["DP-2"]
start = ["workspaces"]
center = []
end = ["systray", "clock"]

[[bars]]
name = "minimal-bar"
edge = "top"
monitors = ["DP-1", "DP-3", "HDMI-A-1"]
start = ["workspaces"]
center = []
end = []

# [[bars]]
# name = "left-bar"
# edge = "left"
# start = []
# center = ["workspaces"]
# end = []


[widgets.workspaces]
indicator_effect = "slide"
indicator_duration_ms = 160
label_format = "%L"
