theme = "personal"

[[bars]]
name = "top-bar"
edge = "top"
start = []
center = ["clock"]
end = ["systray"]

[[bars]]
name = "left-bar"
edge = "left"
start = []
center = ["workspaces"]
end = []


[widgets.workspaces]
indicator_effect = "slide"
indicator_duration_ms = 160
label_format = "%I"
