####################
### APPLICATIONS ###
####################

# Start applications
exec-once = [workspace 1 silent] sh -c 'for i in $(seq 1 100); do busctl --user get-name-owner org.freedesktop.Notifications >/dev/null 2>&1 && break; sleep 0.1; done; uwsm app -- google-chrome-stable'
exec-once = [workspace 2 silent] uwsm app -- ghostty
exec-once = [workspace 3 silent] uwsm app -- code
exec-once = [workspace 4 silent] uwsm app -- vesktop
exec-once = [workspace 5 silent] uwsm app -- obsidian
