#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = numpad:mac
    kb_rules =

    follow_mouse = 1
    mouse_refocus = 0

    accel_profile = adaptive
    sensitivity = 0

    touchpad {
        natural_scroll = true
        tap-to-click = false
        tap-and-drag = false
        clickfinger_behavior = true
        scroll_factor = 0.6
    }
}

################
### GESTURES ###
################

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gesture = 3, horizontal, workspace
hyprexpo-gesture = 3, up, expo

gesture = 2, pinchin, dispatcher, exec, ~/.config/hypr/scripts/gestures.sh pinchin
gesture = 2, pinchout, dispatcher, exec, ~/.config/hypr/scripts/gestures.sh pinchout
gesture = 4, left, dispatcher, exec, ~/.config/hypr/scripts/gestures.sh left
gesture = 4, right, dispatcher, exec, ~/.config/hypr/scripts/gestures.sh right

###############
### DEVICES ###
###############

# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more about per-device configs

# Disable accel on attached mouse
device {
  name = logitech-g-pro--1
  accel_profile = flat
}

# Disable touchscreen on Zenbook S16
device {
  name = elan9008:00-04f3:433b
  enabled = false
}
