#! /bin/sh

pkill compton
compton --config ~/.config/compton.conf -b &

pkill xsettingsd
xsettingsd 2>&1&

pkill insync
insync start 2>&1&

pkill udiskie
udiskie -t 2>&1&

pkill nm-applet
nm-applet >/dev/null 2>&1&

pkill blueman-applet
blueman-applet >/dev/null 2>&1&

#pkill libinput-gestures
#libinput-gestures-setup restart 2>&1&

pkill fluxgui
fluxgui 2>&1&

pkill gebaard
gebaard -b

pkill flameshot
flameshot >/dev/null 2>&1&

pkill pasystray
pasystray >/dev/null 2>&1&

pkill polybar
~/.config/polybar/polybar.sh &

#pkill synergy
#synergy &

xcalib -d :0 ~/.config/icm/B140QAN02_0.icm

feh --randomize --bg-fill ~/Google\ Drive/Apps/Desktoppr/*

#bspc monitor -d I II III IV V VI VII VIII IX X
if [[ $(xrandr -q | egrep '\Wconnected' | wc -l) -eq 1 ]]; then
    m=($(xrandr -q | egrep '\Wconnected' | cut -d' ' -f1))
    bspc monitor -d ${m[1]} I II III IV V VI VII VIII IX X
elif [[ $(xrandr -q | egrep '\Wconnected' | wc -l) -eq 2 ]]; then
    m=($(xrandr -q | egrep '\Wconnected' | cut -d' ' -f1))
    bspc monitor ${m[1]} -d I II III IV V
    bspc monitor ${m[2]} -d VI VII VIII IX X
fi

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config click_to_focus	     true
bspc config auto_cancel 	     true
bspc config presel_border_color  "#ffffff"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config ignore_ewmh_fullscreen "none"

bspc rule -a 'Google-chrome:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb' state=floating
bspc rule -a 'Pavucontrol' state=floating
bspc rule -a 'insync.py' state=floating
bspc rule -a 'Blueman-manager' state=floating
