################
### KEYWORDS ###
################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Terminal
#$terminal = wezterm
$terminal = ghostty

# File manager
$fileManager = thunar

# Launcher
$launcher = rofi -icon-theme "Papirus" -show-icons -no-lazy-grab
#$launcher = fuzzel --output=$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .name')
$emoji = BEMOJI_PICKER_CMD="fuzzel --match-mode exact -d" bemoji -n -t

# Copy Menu
#$copyMenu = wezterm -e --class clipse 'clipse'
$copyMenu = clipse-gui
#$copyMenu = copyq toggle

# Hyprlock
$hyprlock = hyprlock
