{ inputs, ... }:
{
  flake.modules.homeManager.hyprland = { config, lib, pkgs, ... }: {
    options.my.home.hyprland.monitors = lib.mkOption {
      type = lib.types.lines;
      default = ''
        monitor=,preferred,auto,1.0

        xwayland {
          force_zero_scaling = true
        }
      '';
      description = ''
        Full content written to ~/.config/hypr/hyprland/monitors.conf.
        Override per-host for hidpi / multi-monitor setups.
      '';
    };

    config = {
      home.packages = (with pkgs; [
        # Launchers / shell UI
        wofi
        fuzzel
        rofi
        wlogout
        quickshell

        # Hyprland ecosystem
        hyprpolkitagent
        hypridle
        hyprshell
        hyprlock

        # Clipboard / input
        copyq
        clipse
        clipse-gui
        wtype

        # Wallpaper daemon
        awww

        # Keyboard remap helper (system service also enables this via the keyd module)
        keyd
      ]) ++ [ inputs.matugen.packages.${pkgs.stdenv.hostPlatform.system}.default ];

      wayland.windowManager.hyprland = {
        enable = true;
        package = null;
        portalPackage = null;
        extraConfig = ''
          autogenerated = 0

          source = ~/.config/hypr/hyprland/catppuccin.conf
          source = ~/.config/hypr/hyprland/monitors.conf
          source = ~/.config/hypr/hyprland/keywords.conf
          source = ~/.config/hypr/hyprland/autostart.conf
          source = ~/.config/hypr/hyprland/laptop.conf
          source = ~/.config/hypr/hyprland/envvars.conf
          source = ~/.config/hypr/hyprland/layout.conf
          source = ~/.config/hypr/hyprland/windowrules.conf
          source = ~/.config/hypr/hyprland/workspaces.conf
          source = ~/.config/hypr/hyprland/input.conf
          source = ~/.config/hypr/hyprland/keybindings.conf
          source = ~/.config/hypr/hyprland/plugins.conf
          source = ~/.config/hypr/hyprland/autolaunch.conf
        '';
        plugins = [
          inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprexpo
          inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprbars
        ];
      };

      home.file.".config/hypr" = {
        source = ../../config/hypr;
        recursive = true;
      };

      home.file.".config/hypr/hyprland/monitors.conf".text = config.my.home.hyprland.monitors;

      home.file.".config/quickshell" = {
        source = ../../config/quickshell;
        recursive = true;
      };

      home.file.".config/rofi" = {
        source = ../../config/rofi;
        recursive = true;
      };

      home.file.".config/awww" = {
        source = ../../config/awww;
        recursive = true;
      };

      home.file.".config/matugen" = {
        source = ../../config/matugen;
        recursive = true;
      };

      systemd.user.services.awww = {
        Unit = {
          Description = "Animated wallpaper daemon";
          After = [ "graphical-session.target" ];
          PartOf = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = "${pkgs.awww}/bin/awww-daemon -f xrgb";
          Environment = [ "RUST_BACKTRACE=1" ];
          Restart = "on-failure";
          RestartSec = 5;
        };
        Install = {
          WantedBy = [ "graphical-session.target" ];
        };
      };

      systemd.user.services.awww-change-wallpaper = {
        Unit = {
          Description = "Change wallpaper using awww";
          After = [ "awww.service" ];
          Requires = [ "awww.service" ];
        };
        Service = {
          Type = "oneshot";
          ExecStart = "%h/.config/awww/awww_randomize_multi.sh %h/Pictures/Wallpapers";
        };
      };

      systemd.user.timers.awww-change-wallpaper = {
        Unit.Description = "Rotate wallpaper periodically";
        Timer = {
          OnUnitActiveSec = "60min";
        };
        Install.WantedBy = [ "timers.target" ];
      };

      systemd.user.services.quickshell = {
        Unit = {
          Description = "Quickshell";
          After = [ "graphical-session.target" ];
          PartOf = [ "graphical-session.target" ];
        };
        Service = {
          Type = "simple";
          ExecStart = "/etc/profiles/per-user/sboynton/bin/qs";
          Environment = [
            "XDG_DATA_DIRS=/etc/profiles/per-user/sboynton/share:/run/current-system/sw/share:/usr/share"
            "QT_QPA_PLATFORMTHEME=qt6ct"
            "QT_ICON_THEME=Papirus-Dark"
            "QT_STYLE_OVERRIDE=Fusion"
          ];
          Restart = "always";
          RestartSec = "10s";
        };
        Install = {
          WantedBy = [ "graphical-session.target" ];
        };
      };
    };
  };
}
