source = ~/.config/hypr/colors.conf

background {
  monitor=
  blur_passes=1
  blur_size=7
  noise=0.011700
  path=screenshot
}

background {
  monitor=
  blur_passes=1
  blur_size=7
  noise=0.011700
  path=screenshot
}

input-field {
  monitor=
  size=200,50
  check_color=$secondary
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.350000
  fade_on_empty=false
  font_color=$secondary
  halign=center
  hide_input=false
  inner_color=$inverse_primary
  outer_color=$primary
  outline_thickness=2
  placeholder_text=<i><span>Input Password...</span></i>
  position=0, -100
  rounding=-1
  valign=center
}

label {
  monitor=
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrains Mono
  font_size=95
  halign=center
  position=0, 300
  text=$TIME
  valign=center
}

label {
  monitor=
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrains Mono
  font_size=22
  halign=center
  position=0, 200
  text=cmd[update:1000] echo $(date +"%A, %B %d")
  valign=center
}
