#! /bin/sh

pkill sxhkd
sxhkd &

pkill compton
compton --config ~/.config/compton.conf -b &

pkill polybar
~/.i3/polybar.sh &

pkill synergy
synergy &

xinput set-prop 15 "libinput Accel Speed" -0.65

xsetroot -cursor_name left_ptr

feh --randomize --bg-fill ~/samlingx@gmail.com/Apps/Desktoppr/*

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true
bspc config auto_cancel 	 true
bspc config presel_border_color  "#9a875f"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a nvidia-settings state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'Google-chrome:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb' state=floating
bspc rule -a 'Pavucontrol' state=floating
