#! /bin/sh

pkill compton
compton --config ~/.config/compton.conf -b &

pkill insync
insync start 2>&1&

pkill blueman-applet
blueman-applet >/dev/null 2>&1&

pkill libinput-gestures
libinput-gestures-setup start 2>&1&

pkill flameshot
flameshot >/dev/null 2>&1&

pkill pasystray
pasystray >/dev/null 2>&1&

pkill polybar
~/.config/polybar/polybar.sh &

#pkill synergy
#synergy &

feh --randomize --bg-fill ~/Google\ Drive/Apps/Desktoppr/*

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	     true
bspc config auto_cancel 	     true
bspc config presel_border_color  "#ffffff"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config ignore_ewmh_fullscreen "none"

bspc rule -a 'Google-chrome:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb' state=floating
bspc rule -a 'Pavucontrol' state=floating
bspc rule -a 'insync.py' state=floating
bspc rule -a 'Blueman-manager' state=floating
