# /etc/keyd/default.conf
# After making config changes, apply with `sudo keyd reload`

[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

f23+leftshift+leftmeta = M-A-c

[control+alt]
