arch = { packages = [
  "accountsservice",
  "aspell",
  "base",
  "bash-completion",
  "chezmoi",
  "diffutils",
  "downgrade",
  "ex-vi-compat",
  "haveged",
  "less",
  "logrotate",
  "lsb-release",
  "man-pages",
  "metapac",
  "nano",
  "nano-syntax-highlighting",
  "nix",
  "ntp",
  "paru",
  "perl",
  "pkgfile",
  "plocate",
  "python",
  "s-nail",
  "sudo",
  "systemd-sysvcompat",
  "texinfo",
  "which",
  "xdg-user-dirs",
  "xdg-utils",
  "yay",
] }
