arch = { packages = [
  "btrfs-progs",
  "cryptsetup",
  "device-mapper",
  "dmraid",
  "e2fsprogs",
  "exfatprogs",
  "f2fs-tools",
  "jfsutils",
  "lvm2",
  "mdadm",
  "mtools",
  "nfs-utils",
  "nilfs-utils",
  "ntfs-3g",
  "xfsprogs",
] }
