arch = { packages = [
  "alsa-firmware",
  "alsa-plugins",
  "alsa-tools",
  "alsa-utils",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "libdvdcss",
  "pipewire-alsa",
  "pipewire-jack",
  "pipewire-pulse",
  "rtkit",
  "sof-firmware",
  "wireplumber",
] }
