arch = { packages = [
  "bind",
  "dnsmasq",
  "ipcalc",
  "modemmanager",
  "netctl",
  "networkmanager-openconnect",
  "networkmanager-openvpn",
  "nmap",
  "nss-mdns",
  "openbsd-netcat",
  "smbclient",
  "socat",
  "tailscale",
  "traceroute",
  "usb_modeswitch",
  "whois",
  "wireshark-qt",
  "wpa_supplicant",
  "xl2tpd",
] }
