arch = { packages = [
  "acpi_call",
  "amdgpu_top",
  "b43-fwcutter",
  "blueman",
  "bluez",
  "bluez-utils",
  "brightnessctl",
  "cpupower",
  "cpupower-gui-git",
  "dmidecode",
  "ethtool",
  "evtest",
  "geoclue",
  "hdparm",
  "hwdetect",
  "hwinfo",
  "inxi",
  "lsscsi",
  "perf",
  "power-profiles-daemon",
  "radeontop",
  "read-edid",
  "sg3_utils",
  "smartmontools",
  "sysfsutils",
  "turbostat",
  "upower",
  "usbutils",
  "wireless-regdb",
] }
