arch = { packages = [
  "greetd",
  "greetd-regreet",
  "keyd",
  "ly",
  "man-db",
  "network-manager-applet",
  "networkmanager",
  "nm-connection-editor",
  "pacman-contrib",
  "sddm-git",
  "uwsm",
] }
