arch = { packages = [
  "bemoji",
  "cage",
  "cliphist",
  "clipse",
  "clipse-gui",
  "fuzzel",
  "grimblast-git",
  "rofi",
  "satty",
  "waybar",
  "waybar-module-pacman-updates-git",
  "wev",
  "wf-recorder",
  "wl-clipboard",
  "wlogout",
  "wofi-emoji",
  "ydotool",
] }
