arch = { packages = [
  "apple-fonts",
  "cantarell-fonts",
  "gsfonts",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "noto-fonts-extra",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-fira-sans",
  "ttf-iosevka",
  "ttf-iosevka-term",
  "ttf-liberation",
  "ttf-ms-fonts",
  "ttf-opensans",
] }
