arch = { packages = [
  "appimagelauncher",
  "awww",
  "copyq",
  "discord",
  "evolution",
  "firefox",
  "flatpak",
  "foot",
  "ghostty",
  "google-chrome",
  "handlr-regex",
  "insync",
  "kitty",
  "localsend-bin",
  "meld",
  "obsidian",
  "parsec-bin",
  "plasmasys",
  "qt6-virtualkeyboard",
  "redshift",
  "signal-desktop",
  "spotify-launcher",
  "thunar",
  "thunar-volman",
  "vesktop",
  "virtualbox",
  "wezterm",
  "zoom",
] }
