arch = { packages = [
  "aconfmgr-git",
  "asdf-vm",
  "cmake",
  "devtools",
  "gitmux",
  "go",
  "gopls",
  "lazygit",
  "llvm",
  "lua-language-server",
  "luarocks",
  "markdownlint",
  "meson",
  "mmdr-bin",
  "neovim",
  "nvm",
  "patchelf",
  "pyenv",
  "python-defusedxml",
  "python-jinja",
  "python-packaging",
  "rustup",
  "uv",
  "visual-studio-code-bin",
] }
