arch = { packages = [
  "aws-cli",
  "azure-cli",
  "docker",
  "docker-buildx",
  "helm",
  "k9s",
  "kubecolor",
  "kubectl",
  "kubescape",
  "kubie",
  "terraform",
  "terragrunt",
  "vendir",
  "ytt",
] }
