# baremetal: kernel, boot, hardware, filesystems, login manager
arch = { packages = [
  # kernel
  "amd-ucode",
  "linux",
  "linux-firmware",
  "linux-headers",
  "linux-lts",
  "linux-lts-headers",

  # boot
  "dosfstools",
  "dracut",
  "efibootmgr",
  "efitools",
  "grub",
  "os-prober",

  # filesystems
  "btrfs-assistant",
  "btrfs-progs",
  "cryptsetup",
  "device-mapper",
  "dmraid",
  "e2fsprogs",
  "exfatprogs",
  "f2fs-tools",
  "jfsutils",
  "lvm2",
  "mdadm",
  "mtools",
  "nfs-utils",
  "nilfs-utils",
  "ntfs-3g",
  "snapper",
  "xfsprogs",

  # hardware
  "acpi_call",
  "amdgpu_top",
  "b43-fwcutter",
  "blueman",
  "bluez",
  "bluez-utils",
  "brightnessctl",
  "cpupower",
  "cpupower-gui-git",
  "dmidecode",
  "ethtool",
  "evtest",
  "geoclue",
  "hdparm",
  "hwdetect",
  "hwinfo",
  "inxi",
  "keyd",
  "lsscsi",
  "nvidia-settings",
  "perf",
  "power-profiles-daemon",
  "radeontop",
  "read-edid",
  "sg3_utils",
  "smartmontools",
  "snapd",
  "sysfsutils",
  "turbostat",
  "upower",
  "usbutils",
  "wireless-regdb",

  # login / session managers
  "greetd",
  "greetd-regreet",
  "ly",
  "sddm-git",

  # desktop system services
  "gvfs",
  "tumbler",
  "udiskie",
] }
