# core
arch = { packages = [
  "7zip",
  "base-devel",
  "git",
  "git-delta",
  "github-cli",
  "openssh",
  "rsync",
  "tmux",
  "unrar",
  "unzip",
  "wget",
  "zsh",

  # base-system
  "accountsservice",
  "aspell",
  "base",
  "bash-completion",
  "chezmoi",
  "diffutils",
  "downgrade",
  "ex-vi-compat",
  "haveged",
  "less",
  "logrotate",
  "lsb-release",
  "man-pages",
  "metapac",
  "nano",
  "nano-syntax-highlighting",
  "nix",
  "ntp",
  "paru",
  "perl",
  "pkgfile",
  "plocate",
  "python",
  "s-nail",
  "sudo",
  "systemd-sysvcompat",
  "texinfo",
  "which",
  "xdg-user-dirs",
  "xdg-utils",
  "yay",

  # kernel
  "amd-ucode",
  "linux",
  "linux-firmware",
  "linux-headers",
  "linux-lts",
  "linux-lts-headers",

  # boot
  "dosfstools",
  "dracut",
  "efibootmgr",
  "efitools",
  "grub",
  "os-prober",

  # endeavouros
  "endeavouros-branding",
  "endeavouros-keyring",
  "endeavouros-mirrorlist",
  "eos-apps-info",
  "eos-dracut",
  "eos-hooks",
  "eos-log-tool",
  "eos-packagelist",
  "eos-quickstart",
  "eos-rankmirrors",
  "rebuild-detector",
  "reflector",
  "reflector-simple",
  "welcome",

  # filesystems
  "btrfs-progs",
  "cryptsetup",
  "device-mapper",
  "dmraid",
  "e2fsprogs",
  "exfatprogs",
  "f2fs-tools",
  "jfsutils",
  "lvm2",
  "mdadm",
  "mtools",
  "nfs-utils",
  "nilfs-utils",
  "ntfs-3g",
  "xfsprogs",

  # audio
  "alsa-firmware",
  "alsa-plugins",
  "alsa-tools",
  "alsa-utils",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "libdvdcss",
  "pipewire-alsa",
  "pipewire-jack",
  "pipewire-pulse",
  "rtkit",
  "sof-firmware",
  "wireplumber",

  # network
  "bind",
  "dnsmasq",
  "ipcalc",
  "modemmanager",
  "netctl",
  "networkmanager-openconnect",
  "networkmanager-openvpn",
  "nmap",
  "nss-mdns",
  "openbsd-netcat",
  "smbclient",
  "socat",
  "tailscale",
  "traceroute",
  "usb_modeswitch",
  "whois",
  "wireshark-qt",
  "wpa_supplicant",
  "xl2tpd",

  # firewall
  "firewall-applet",
  "firewalld",
  "iptables",

  # printing
  "cups",
  "cups-browsed",
  "cups-filters",
  "cups-pdf",
  "foomatic-db",
  "foomatic-db-engine",
  "foomatic-db-gutenprint-ppds",
  "foomatic-db-nonfree",
  "foomatic-db-nonfree-ppds",
  "foomatic-db-ppds",
  "ghostscript",
  "gutenprint",
  "splix",
  "system-config-printer",

  # xorg
  "mesa-utils",
  "vulkan-headers",
  "xf86-input-libinput",
  "xf86-video-amdgpu",
  "xf86-video-ati",
  "xorg-server",
  "xorg-xdpyinfo",
  "xorg-xinit",
  "xorg-xinput",
  "xorg-xkill",
  "xorg-xrandr",
  "xterm",

  # system-libs
  "libconfig",
  "libinput-tools",

  # system-services
  "greetd",
  "greetd-regreet",
  "keyd",
  "ly",
  "man-db",
  "network-manager-applet",
  "networkmanager",
  "nm-connection-editor",
  "pacman-contrib",
  "sddm-git",
  "uwsm",

  # monitoring
  "btop",
  "bustle",
  "d-spy",
  "dua-cli",
  "duf",
  "fastfetch",
  "glances",
  "htop",
  "imv",
  "serie",
  "syshud",
  "tldr",
  "viddy",
  "viu",

  # file-management
  "btrfs-assistant",
  "dialog",
  "gvfs",
  "perl-file-mimeinfo",
  "restic",
  "snapper",
  "tumbler",
  "udiskie",

  # security
  "arp-scan",
  "certbot",

  # hardware
  "acpi_call",
  "amdgpu_top",
  "b43-fwcutter",
  "blueman",
  "bluez",
  "bluez-utils",
  "brightnessctl",
  "cpupower",
  "cpupower-gui-git",
  "dmidecode",
  "ethtool",
  "evtest",
  "geoclue",
  "hdparm",
  "hwdetect",
  "hwinfo",
  "inxi",
  "lsscsi",
  "perf",
  "power-profiles-daemon",
  "radeontop",
  "read-edid",
  "sg3_utils",
  "smartmontools",
  "sysfsutils",
  "turbostat",
  "upower",
  "usbutils",
  "wireless-regdb",

  # terminal
  "zellij",

  # media
  "chafa",
  "feh",
  "ffmpegthumbnailer",
  "icat",
  "libgsf",
  "libopenraw",
  "mirage",
  "mpv",
  "pavucontrol",
  "poppler-glib",
  "timg",
  "vlc",
  "vlc-plugins-all",
  "yt-dlp",
] }
