# desktop apps
arch = { packages = [
  "appimagelauncher",
  "awww",
  "aylurs-gtk-shell-git",
  "copyq",
  "discord",
  "evolution",
  "firefox",
  "flatpak",
  "foot",
  "ghostty",
  "handlr-regex",
  "insync",
  "kitty",
  "meld",
  "obsidian",
  "parsec-bin",
  "plasmasys",
  "qt6-virtualkeyboard",
  "redshift",
  "signal-desktop",
  "spotify-launcher",
  "thunar",
  "thunar-volman",
  "vesktop",
  "virtualbox",
  "wezterm",
  "zoom",

  # themes
  "catppuccin-gtk-theme-mocha",
  "font-manager",
  "matugen-bin",
  "numix-circle-icon-theme-git",
  "nwg-look",
  "papirus-icon-theme",
  "python-pywal16",
  "qt6ct",

  # gnome
  "gnome-keyring",
  "gnome-power-manager",
  "gnome-themes-extra",

  # gui-framework
  "gtk3",
  "gtk4",
  "hyprswitch",
] }
