# cli-tools
arch = { packages = [
  "bat",
  "direnv",
  "doppler-cli-bin",
  "eza",
  "fx",
  "glow",
  "go-yq",
  "grc",
  "gron",
  "jc",
  "jq",
  "just",
  "lsd",
  "pet-git",
  "tree",
  "zoxide",

  # build tools
  "autoconf",
  "automake",
  "bison",
  "flex",
  "gcc",
  "pkgconf",

  # development
  "aconfmgr-git",
  "asdf-vm",
  "cmake",
  "devtools",
  "gitmux",
  "go",
  "gopls",
  "lazygit",
  "llvm",
  "lua-language-server",
  "luarocks",
  "markdownlint",
  "meson",
  "mmdr-bin",
  "neovim",
  "nvm",
  "patchelf",
  "pyenv",
  "python-defusedxml",
  "python-jinja",
  "python-packaging",
  "rustup",
  "uv",
  "visual-studio-code-bin",

  # dev utilities
  "claude-code-seccomp",
  "docker-sandbox-bin",
  "expect",
  "git-filter-repo",
  "git-lfs",
  "mingw-w64-gcc",
  "pgloader",
  "postgresql",
  "pre-commit",
  "trufflehog",
  "websocat",

  # cloud
  "ansible",
  "argocd",
  "aws-cli",
  "azure-cli",
  "cilium-cli",
  "docker",
  "docker-buildx",
  "helm",
  "hubble-bin",
  "k9s",
  "kopia",
  "kube-apiserver",
  "kubecolor",
  "kubectl",
  "kubescape",
  "kubie",
  "minikube",
  "skopeo",
  "talhelper",
  "terraform",
  "terragrunt",
  "vendir",
  "ytt",

  # ai
  "aichat",

  # utilities
  "graphviz",
] }
