# media apps and GUI viewers
arch = { packages = [
  "bustle",
  "d-spy",
  "feh",
  "ffmpegthumbnailer",
  "imv",
  "libgsf",
  "libopenraw",
  "mirage",
  "mpv",
  "pavucontrol",
  "poppler-glib",
  "syshud",
  "vlc",
  "vlc-plugins-all",
  "yt-dlp",
] }
