# network services and GUI tools (CLI nets live in common)
arch = { packages = [
  "dnsmasq",
  "modemmanager",
  "netctl",
  "network-manager-applet",
  "networkmanager",
  "networkmanager-openconnect",
  "networkmanager-openvpn",
  "nm-connection-editor",
  "nss-mdns",
  "usb_modeswitch",
  "wireshark-qt",
  "wpa_supplicant",
  "xl2tpd",

  # firewall
  "firewall-applet",
  "firewalld",
  "iptables",
] }
