# printing
arch = { packages = [
  "cups",
  "cups-browsed",
  "cups-filters",
  "cups-pdf",
  "foomatic-db",
  "foomatic-db-engine",
  "foomatic-db-gutenprint-ppds",
  "foomatic-db-nonfree",
  "foomatic-db-nonfree-ppds",
  "foomatic-db-ppds",
  "ghostscript",
  "gutenprint",
  "splix",
  "system-config-printer",
] }
