# wayland
arch = { packages = [
  "bemoji",
  "cage",
  "cliphist",
  "clipse",
  "clipse-gui",
  "fuzzel",
  "grimblast-git",
  "rofi",
  "satty",
  "waybar",
  "waybar-module-pacman-updates-git",
  "wev",
  "wf-recorder",
  "wl-clipboard",
  "wlogout",
  "wofi-emoji",
  "ydotool",

  # hyprland
  "hyprdynamicmonitors-bin",
  "hypridle",
  "hyprland",
  "hyprland-qt-support",
  "hyprlang",
  "hyprlock",
  "hyprpaper",
  "hyprpicker",
  "hyprpolkitagent",
  "hyprshot",
  "hyprutils",
  "quickshell",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
] }
