{
  description = "NixOS base flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1&ref=v0.48.1-b";

    hy3 = {
      url = "github:outfoxxed/hy3";
      inputs.hyprland.follows = "hyprland";
    };
  };

  outputs = {
    self,
    nixpkgs,
    home-manager,
    hyprland,
    hy3,
    ...
  } @ inputs: let
    inherit (self) outputs;
  in {
    nixosConfigurations = {
      nixos = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit inputs outputs; };
        modules = [
          ./configuration.nix
        ];
      };
    };
    homeConfigurations = {
      "sboynton@nixos" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux;
        extraSpecialArgs = { inherit inputs; };
        modules = [
          hyprland.homeManagerModules.default
          {
            wayland.windowManager.hyprland = {
              enable = true;
              extraConfig = ''
                # https://wiki.hyprland.org/Configuring/
                
                autogenerated = 0
                
                source = ~/.config/hypr/hyprland/monitors.conf
                source = ~/.config/hypr/hyprland/keywords.conf
                source = ~/.config/hypr/hyprland/autostart.conf
                source = ~/.config/hypr/hyprland/laptop.conf
                source = ~/.config/hypr/hyprland/envvars.conf
                source = ~/.config/hypr/hyprland/layout.conf
                source = ~/.config/hypr/hyprland/windowrules.conf
                source = ~/.config/hypr/hyprland/workspaces.conf
                source = ~/.config/hypr/hyprland/input.conf
                source = ~/.config/hypr/hyprland/keybindings.conf
                source = ~/.config/hypr/hyprland/autolaunch.conf
                source = ~/.config/hypr/hyprland/plugins.conf
                source = ~/.config/hypr/hyprland/bar.conf
                '';
              };
            }
          ./home.nix
        ];
      };
    }; 
  };
}
