settings:
    additional_configs:
        - snippets/*.yaml
    interactive:
        confirm_before_execute: false
        show_final_command: true
    selector:
        command: fzf
        options: --height 60% --reverse --border --sort --bind ctrl-u:page-up --bind ctrl-d:page-down
