-- Generated by Matugen: catppuccin color overrides from Material You palette
return {
  -- Base/background colors
  base = "{{colors.background.default.hex}}",
  mantle = "{{colors.surface_container_lowest.default.hex}}",
  crust = "{{colors.surface_container_low.default.hex}}",

  -- Foreground colors
  text = "{{colors.on_surface.default.hex}}",
  subtext1 = "{{colors.on_surface_variant.default.hex}}",
  subtext0 = "{{colors.outline.default.hex}}",

  -- Overlay colors
  overlay2 = "{{colors.outline_variant.default.hex}}",
  overlay1 = "{{colors.outline.default.hex}}",
  overlay0 = "{{colors.surface_bright.default.hex}}",

  -- Surface colors
  surface2 = "{{colors.surface_container_high.default.hex}}",
  surface1 = "{{colors.surface_container.default.hex}}",
  surface0 = "{{colors.surface_container_low.default.hex}}",

  -- Accent colors
  blue = "{{colors.primary.default.hex}}",
  lavender = "{{colors.primary_container.default.hex}}",
  sapphire = "{{colors.primary.default.hex | lighten: -10}}",
  sky = "{{colors.tertiary.default.hex | lighten: -10}}",
  teal = "{{colors.tertiary.default.hex}}",
  green = "{{colors.tertiary.default.hex | lighten: -15}}",
  yellow = "{{colors.secondary.default.hex}}",
  peach = "{{colors.secondary.default.hex | lighten: -10}}",
  maroon = "{{colors.error.default.hex | lighten: -10}}",
  red = "{{colors.error.default.hex}}",
  mauve = "{{colors.secondary_container.default.hex}}",
  pink = "{{colors.tertiary_container.default.hex}}",
  flamingo = "{{colors.error_container.default.hex}}",
  rosewater = "{{colors.on_error_container.default.hex}}",
}
