enabled_backends = ["arch"]
hostname_groups_enabled = true

[arch]
package_manager = "paru"

[hostname_groups]
antares = ["common", "baremetal", "audio", "network", "printing", "xorg", "endeavouros", "media", "virtualization", "dev", "fonts", "gui-essentials", "desktop", "wayland"]
apollo = ["common", "baremetal", "audio", "network", "printing", "xorg", "endeavouros", "media", "virtualization", "dev", "fonts", "gui-essentials", "desktop", "wayland", "laptop", "asus"]
endeavor = ["common", "baremetal", "audio", "network", "printing", "xorg", "endeavouros", "media", "virtualization", "dev", "fonts", "gui-essentials", "desktop", "wayland"]
icarus = ["common", "baremetal", "audio", "network", "printing", "xorg", "endeavouros", "media", "virtualization", "dev", "fonts", "gui-essentials", "desktop", "wayland", "laptop"]
xen = ["common", "baremetal", "audio", "network", "printing", "xorg", "endeavouros", "media", "virtualization", "dev", "fonts", "gui-essentials", "desktop", "wayland", "laptop", "asus", "gaming"]
Sam-Desktop = ["common", "dev", "gui-essentials", "virtualization"]
