[ids]
*

[main]
capslock = leftcontrol

# swap leftalt/leftmeta
leftalt=leftmeta
leftmeta=leftalt

# launch clipse-gui
f23+leftshift+leftmeta = M-A-c

# right-alt closes tab on tap
rightalt = overload(ralt, C-w)

# right-shift + right-alt reopens tab on tap
rightshift = overload(rshift, rightshift)

[rshift:S]
rightalt = C-S-t

[ralt:A]
rightshift = C-S-t

# Empty layer declarations so app.conf can bind on these chords.
[control+alt]

[shift+alt]
