[ids]
*

[main]
capslock = leftcontrol
#leftalt=leftmeta
#leftmeta=leftalt
f23+leftshift+leftmeta = M-A-c
rightalt = overload(ralt, C-w)
rightshift = overload(rshift, rightshift)

[rshift:S]
rightalt = C-S-t

[ralt:A]
rightshift = C-S-t

# Empty layer declarations so app.conf can bind on these chords.
[control+alt]

[shift+alt]
