pragma Singleton

import QtQuick

// Default colors — overwritten at runtime by matugen
QtObject {

    readonly property color background: "#151217"
    readonly property color error: "#ffb4ab"
    readonly property color error_container: "#93000a"
    readonly property color inverse_on_surface: "#332f35"
    readonly property color inverse_primary: "#705289"
    readonly property color inverse_surface: "#e8e0e8"
    readonly property color on_background: "#e8e0e8"
    readonly property color on_error: "#690005"
    readonly property color on_error_container: "#ffdad6"
    readonly property color on_primary: "#402357"
    readonly property color on_primary_container: "#f1daff"
    readonly property color on_primary_fixed: "#290c41"
    readonly property color on_primary_fixed_variant: "#573a70"
    readonly property color on_secondary: "#372c3f"
    readonly property color on_secondary_container: "#eeddf6"
    readonly property color on_secondary_fixed: "#211829"
    readonly property color on_secondary_fixed_variant: "#4e4256"
    readonly property color on_surface: "#e8e0e8"
    readonly property color on_surface_variant: "#cdc4ce"
    readonly property color on_tertiary: "#4c2529"
    readonly property color on_tertiary_container: "#ffdadc"
    readonly property color on_tertiary_fixed: "#321015"
    readonly property color on_tertiary_fixed_variant: "#663a3f"
    readonly property color outline: "#968e98"
    readonly property color outline_variant: "#4b454d"
    readonly property color primary: "#ddb9f8"
    readonly property color primary_container: "#573a70"
    readonly property color primary_fixed: "#f1daff"
    readonly property color primary_fixed_dim: "#ddb9f8"
    readonly property color scrim: "#000000"
    readonly property color secondary: "#d1c1d9"
    readonly property color secondary_container: "#4e4256"
    readonly property color secondary_fixed: "#eeddf6"
    readonly property color secondary_fixed_dim: "#d1c1d9"
    readonly property color shadow: "#000000"
    readonly property color source_color: "#a58cb7"
    readonly property color surface: "#151217"
    readonly property color surface_bright: "#3c383e"
    readonly property color surface_container: "#221e24"
    readonly property color surface_container_high: "#2d292e"
    readonly property color surface_container_highest: "#383339"
    readonly property color surface_container_low: "#1e1a20"
    readonly property color surface_container_lowest: "#100d12"
    readonly property color surface_dim: "#151217"
    readonly property color surface_tint: "#ddb9f8"
    readonly property color surface_variant: "#4b454d"
    readonly property color term_blue: "#b8c4ff"
    readonly property color term_blue_container: "#374379"
    readonly property color term_blue_source: "#89b4fa"
    readonly property color term_blue_value: "#89b4fa"
    readonly property color term_cyan: "#80d4d7"
    readonly property color term_cyan_container: "#004f52"
    readonly property color term_cyan_source: "#94e2d5"
    readonly property color term_cyan_value: "#94e2d5"
    readonly property color term_green: "#91d5ad"
    readonly property color term_green_container: "#035233"
    readonly property color term_green_source: "#a6e3a1"
    readonly property color term_green_value: "#a6e3a1"
    readonly property color term_magenta: "#dbb9f9"
    readonly property color term_magenta_container: "#563b71"
    readonly property color term_magenta_source: "#cba6f7"
    readonly property color term_magenta_value: "#cba6f7"
    readonly property color term_orange: "#ffb59d"
    readonly property color term_orange_container: "#723520"
    readonly property color term_orange_source: "#fab387"
    readonly property color term_orange_value: "#fab387"
    readonly property color term_red: "#fbb0d8"
    readonly property color term_red_container: "#6c3455"
    readonly property color term_red_source: "#f38ba8"
    readonly property color term_red_value: "#f38ba8"
    readonly property color term_yellow: "#f5bd6f"
    readonly property color term_yellow_container: "#633f00"
    readonly property color term_yellow_source: "#f9e2af"
    readonly property color term_yellow_value: "#f9e2af"
    readonly property color tertiary: "#f3b7bc"
    readonly property color tertiary_container: "#663a3f"
    readonly property color tertiary_fixed: "#ffdadc"
    readonly property color tertiary_fixed_dim: "#f3b7bc"

}
